# perulangan (loop)

# for kondisi : JIKA KONDISI TERPENUHI
#     aksi JALANKAN ASKI

angka_list = [0,2,4,8,10] # ini adalah list
print(angka_list)
 
# angka =0
# print(angka)
# angka += 1 # angka = angka +1
# print (angka)
# angka += 1
# print (angka)

# for-loop
for i in angka_list:
    print(f" i yang sekrang -> {i}")

print("loop berakhir \n")


# perulangan (loop)

# for kondisi : JIKA KONDISI TERPENUHI
#     aksi JALANKAN ASKI

range = [0,2,4,8,10] # ini adalah range
print(range)
 
# angka =0
# print(angka)
# angka += 1 # angka = angka +1
# print (angka)
# angka += 1
# print (angka)

# for-loop
for i in range:
    print(f" i yang sekrang -> {i}")

print("loop berakhir \n")

range = [1,2,3] # ini adalah range
print(range)
 
# angka =0
# print(angka)
# angka += 1 # angka = angka +1
# print (angka)
# angka += 1
# print (angka)

# for-loop
for i in range:
    print("*" * i)

print("loop berakhir \n")

